version: '3.8'

services:

  ms-discovery:
    build:
      context: ./discovery
      dockerfile: ./docker/Dockerfile
    container_name: ms-discovery
    ports:
      - "8761:8761"

  ms-gateway:
    build:
      context: ./gateway
      dockerfile: ./docker/Dockerfile
    container_name: ms-gateway
    depends_on:
      - ms-article
      - ms-user
    ports:
      - "8088:8088"

  ms-user:
    build:
      context: ./user
      dockerfile: ./docker/Dockerfile
    container_name: ms-user
    depends_on:
      - database
    ports:
      - "8081:8081"

  ms-article:
    build:
      context: ./article
      dockerfile: ./docker/Dockerfile
    container_name: ms-article
    depends_on:
      - database
    ports:
      - "8082:8082"

  database:
    image: postgres:16.1-alpine
    container_name: database
    depends_on:
      - ms-discovery
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
