apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-discovery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-discovery
  template:
    metadata:
      labels:
        app: ms-discovery
    spec:
      containers:
        - name: ms-discovery-container
          image: spring-microservices-ms-discovery:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761