apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-user
  template:
    metadata:
      labels:
        app: ms-user
    spec:
      containers:
        - name: ms-user-container
          image: spring-microservices-ms-user:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
